# Generated by Django 4.2.16 on 2024-12-02 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название категории')),
                ('description', models.TextField(max_length=1000, verbose_name='Описание категории')),
            ],
            options={
                'verbose_name': 'Категорию',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название блюда')),
                ('description', models.TextField(max_length=2000, verbose_name='Описание блюда')),
                ('steps', models.TextField(max_length=5000, verbose_name='Шаги приготовления блюда')),
                ('time', models.CharField(max_length=60, verbose_name='Время приготовления блюда')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Изображение блюда')),
                ('ingredients', models.TextField(max_length=2000, verbose_name='Ингридиенты')),
                ('date_create', models.DateField(auto_now_add=True, verbose_name='Дата добавления')),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='recipes', related_query_name='recipe', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipes', related_query_name='recipe', to='recipe.category')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
            },
        ),
    ]
